AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  VPC:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  Cluster:
    Description: 'Stack name of parent ECS cluster.'
    Type: String
  DesiredInstances:
    Description: How many instances of this task should we run across our cluster?
    Type: Number
    Default: 2
  Listener:
    Description: The Application Load Balancer listener to register with
    Type: String
#    Default: 'arn:aws:elasticloadbalancing:eu-central-1:508824606728:listener/app/Test/a0aaad35db8ea3b9/3b2d8470eca06dbf'
Resources:

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster: !Ref Cluster
#        'Fn::ImportValue': !Sub '${Cluster}-ClusterName'
      Role: !Ref ServiceRole
      DesiredCount: !Ref DesiredInstances
      TaskDefinition: !Ref ECSTaskDefinition
      LoadBalancers:
        - ContainerName: "nginx"
          ContainerPort: 80
          TargetGroupArn: !Ref ECSTargetGroup

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: nginx
      ContainerDefinitions:
        - Name: nginx
          Essential: true
          Image: nginx
          Memory: 128
          PortMappings:
            - ContainerPort: 80

  ECSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
#        'Fn::ImportValue': !Sub '${VPC}-VPC'
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref Listener
#        'Fn::ImportValue': !Sub '${Cluster}-Listener'
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
          - '/'
      Actions:
        - TargetGroupArn: !Ref ECSTargetGroup
          Type: forward

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecs-service-${AWS::StackName}
      Path: /
      AssumeRolePolicyDocument: |
        {
          "Statement": [{
              "Effect": "Allow",
              "Principal": { "Service": [ "ecs.amazonaws.com" ]},
              "Action": [ "sts:AssumeRole" ]
          }]
        }
      Policies:
        - PolicyName: !Sub ecs-service-${AWS::StackName}
          PolicyDocument:
            {
              "Version": "2012-10-17",
              "Statement": [{
                "Effect": "Allow",
                "Action": [
                    "ec2:AuthorizeSecurityGroupIngress",
                    "ec2:Describe*",
                    "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
                    "elasticloadbalancing:Describe*",
                    "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
                    "elasticloadbalancing:DeregisterTargets",
                    "elasticloadbalancing:DescribeTargetGroups",
                    "elasticloadbalancing:DescribeTargetHealth",
                    "elasticloadbalancing:RegisterTargets"
                ],
                "Resource": "*"
              }]
            }